[2025-03-22T18:18:45.857+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-04T22:00:00+00:00 [queued]>
[2025-03-22T18:18:45.870+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-04T22:00:00+00:00 [queued]>
[2025-03-22T18:18:45.870+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2025-03-22T18:18:45.899+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-04 22:00:00+00:00
[2025-03-22T18:18:45.907+0000] {standard_task_runner.py:60} INFO - Started process 6064 to run task
[2025-03-22T18:18:45.910+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-04T22:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp1c0bm3u_']
[2025-03-22T18:18:45.912+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask gen_data_daily
[2025-03-22T18:18:46.066+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-04T22:00:00+00:00 [running]> on host 8d12aff548d4
[2025-03-22T18:18:46.266+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-04T22:00:00+00:00'
[2025-03-22T18:18:46.267+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-22T18:18:46.269+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-05\n        ']
[2025-03-22T18:18:46.291+0000] {subprocess.py:86} INFO - Output:
[2025-03-22T18:18:48.488+0000] {subprocess.py:93} INFO - Successfully inserted 20000 rows into transaction_data table at 2025-03-05
[2025-03-22T18:18:48.489+0000] {subprocess.py:93} INFO - Table contains 100000 rows
[2025-03-22T18:18:48.489+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-05
[2025-03-22T18:18:48.634+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-22T18:18:48.690+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250304T220000, start_date=20250322T181845, end_date=20250322T181848
[2025-03-22T18:18:48.775+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-22T18:18:48.813+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
