[2025-03-15T17:41:23.673+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.calcaulte_fts scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-03-15T17:41:23.708+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.calcaulte_fts scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-03-15T17:41:23.709+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2025-03-15T17:41:23.737+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): calcaulte_fts> on 2025-03-13 22:00:00+00:00
[2025-03-15T17:41:23.763+0000] {standard_task_runner.py:60} INFO - Started process 1899 to run task
[2025-03-15T17:41:23.781+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'calcaulte_fts', 'scheduled__2025-03-13T22:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp2nd8pdk6']
[2025-03-15T17:41:23.782+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask calcaulte_fts
[2025-03-15T17:41:23.919+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.calcaulte_fts scheduled__2025-03-13T22:00:00+00:00 [running]> on host 1e3bcc32b6c1
[2025-03-15T17:41:24.067+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='calcaulte_fts' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T22:00:00+00:00'
[2025-03-15T17:41:24.069+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-15T17:41:24.070+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/2_calculate_features.py 2025-03-14\n        ']
[2025-03-15T17:41:24.088+0000] {subprocess.py:86} INFO - Output:
[2025-03-15T17:41:31.751+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-03-15T17:41:31.952+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-03-15T17:41:31.953+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-03-15T17:41:31.961+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-03-15T17:41:31.962+0000] {subprocess.py:93} INFO - io.delta#delta-core_2.12 added as a dependency
[2025-03-15T17:41:31.962+0000] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-03-15T17:41:31.962+0000] {subprocess.py:93} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-03-15T17:41:31.966+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-6eec7419-5eb4-43cf-bc71-5d4f595a4b58;1.0
[2025-03-15T17:41:31.967+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-03-15T17:41:32.240+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 in central
[2025-03-15T17:41:32.361+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 in central
[2025-03-15T17:41:32.402+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;3.3.2 in central
[2025-03-15T17:41:32.470+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-03-15T17:41:32.516+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.10.1 in central
[2025-03-15T17:41:32.589+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;2.0.6 in central
[2025-03-15T17:41:32.627+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-03-15T17:41:32.668+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-03-15T17:41:32.709+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-03-15T17:41:32.736+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-03-15T17:41:32.755+0000] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-03-15T17:41:32.784+0000] {subprocess.py:93} INFO - 	found io.delta#delta-core_2.12;2.4.0 in central
[2025-03-15T17:41:32.806+0000] {subprocess.py:93} INFO - 	found io.delta#delta-storage;2.4.0 in central
[2025-03-15T17:41:32.821+0000] {subprocess.py:93} INFO - 	found org.antlr#antlr4-runtime;4.9.3 in central
[2025-03-15T17:41:32.864+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in central
[2025-03-15T17:41:32.907+0000] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-03-15T17:41:32.923+0000] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.12.261 in central
[2025-03-15T17:41:32.971+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 984ms :: artifacts dl 24ms
[2025-03-15T17:41:32.972+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-03-15T17:41:32.972+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.12.261 from central in [default]
[2025-03-15T17:41:32.972+0000] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-03-15T17:41:32.973+0000] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-03-15T17:41:32.973+0000] {subprocess.py:93} INFO - 	io.delta#delta-core_2.12;2.4.0 from central in [default]
[2025-03-15T17:41:32.973+0000] {subprocess.py:93} INFO - 	io.delta#delta-storage;2.4.0 from central in [default]
[2025-03-15T17:41:32.973+0000] {subprocess.py:93} INFO - 	org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2025-03-15T17:41:32.974+0000] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-03-15T17:41:32.974+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from central in [default]
[2025-03-15T17:41:32.975+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2025-03-15T17:41:32.975+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-03-15T17:41:32.975+0000] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;3.3.2 from central in [default]
[2025-03-15T17:41:32.975+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;2.0.6 from central in [default]
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.10.1 from central in [default]
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	:: evicted modules:
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 by [com.amazonaws#aws-java-sdk-bundle;1.12.261] in [default]
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-03-15T17:41:32.976+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-03-15T17:41:32.977+0000] {subprocess.py:93} INFO - 	|      default     |   18  |   0   |   0   |   1   ||   17  |   0   |
[2025-03-15T17:41:32.977+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-03-15T17:41:32.983+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-6eec7419-5eb4-43cf-bc71-5d4f595a4b58
[2025-03-15T17:41:32.984+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-03-15T17:41:32.994+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 17 already retrieved (0kB/11ms)
[2025-03-15T17:41:33.622+0000] {subprocess.py:93} INFO - 25/03/15 17:41:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-15T17:41:34.192+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-03-15T17:41:34.192+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-15T17:41:53.202+0000] {subprocess.py:93} INFO - 25/03/15 17:41:53 ERROR Inbox: Ignoring error
[2025-03-15T17:41:53.203+0000] {subprocess.py:93} INFO - java.lang.NullPointerException
[2025-03-15T17:41:53.203+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:582)
[2025-03-15T17:41:53.203+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-03-15T17:41:53.203+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-03-15T17:41:53.203+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-03-15T17:41:53.203+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-03-15T17:41:53.204+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-03-15T17:41:53.204+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-03-15T17:41:53.204+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-03-15T17:41:53.204+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2025-03-15T17:41:53.204+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-03-15T17:41:53.204+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-03-15T17:41:53.204+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-03-15T17:41:53.205+0000] {subprocess.py:93} INFO - 25/03/15 17:41:53 WARN Executor: Issue communicating with driver in heartbeater
[2025-03-15T17:41:53.205+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-15T17:41:53.205+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:103)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:87)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:643)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1057)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:238)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2025-03-15T17:41:53.206+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-03-15T17:41:53.207+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2025-03-15T17:41:53.207+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2025-03-15T17:41:53.207+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2025-03-15T17:41:53.207+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2025-03-15T17:41:53.207+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-03-15T17:41:53.208+0000] {subprocess.py:93} INFO - Caused by: java.lang.NullPointerException
[2025-03-15T17:41:53.208+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:582)
[2025-03-15T17:41:53.208+0000] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:123)
[2025-03-15T17:41:53.208+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2025-03-15T17:41:53.208+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2025-03-15T17:41:53.208+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2025-03-15T17:41:53.208+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2025-03-15T17:41:53.209+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2025-03-15T17:41:53.209+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2025-03-15T17:41:53.209+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2025-03-15T17:41:53.209+0000] {subprocess.py:93} INFO - 	... 3 more
[2025-03-15T17:42:00.951+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-15T17:42:00.952+0000] {subprocess.py:93} INFO -   File "/opt/***/external_scripts/2_calculate_features.py", line 49, in <module>
[2025-03-15T17:42:00.963+0000] {subprocess.py:93} INFO -     raw_kafka_df = spark.read \
[2025-03-15T17:42:00.963+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/pyspark/sql/readwriter.py", line 184, in load
[2025-03-15T17:42:00.964+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.load())
[2025-03-15T17:42:00.964+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
[2025-03-15T17:42:00.965+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/pyspark/sql/utils.py", line 190, in deco
[2025-03-15T17:42:00.965+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-03-15T17:42:00.965+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-03-15T17:42:00.966+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o51.load.
[2025-03-15T17:42:00.966+0000] {subprocess.py:93} INFO - : java.lang.NullPointerException
[2025-03-15T17:42:00.966+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.kafka010.KafkaSourceProvider.validateGeneralOptions(KafkaSourceProvider.scala:246)
[2025-03-15T17:42:00.966+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.kafka010.KafkaSourceProvider.org$apache$spark$sql$kafka010$KafkaSourceProvider$$validateBatchOptions(KafkaSourceProvider.scala:384)
[2025-03-15T17:42:00.967+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.kafka010.KafkaSourceProvider.createRelation(KafkaSourceProvider.scala:128)
[2025-03-15T17:42:00.967+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
[2025-03-15T17:42:00.967+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-03-15T17:42:00.968+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-03-15T17:42:00.968+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-03-15T17:42:00.968+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-03-15T17:42:00.969+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:171)
[2025-03-15T17:42:00.969+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-15T17:42:00.970+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-15T17:42:00.970+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-15T17:42:00.970+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-03-15T17:42:00.971+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-15T17:42:00.971+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-03-15T17:42:00.972+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-15T17:42:00.972+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-15T17:42:00.972+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-15T17:42:00.972+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-15T17:42:00.973+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-15T17:42:00.973+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-03-15T17:42:00.973+0000] {subprocess.py:93} INFO - 
[2025-03-15T17:42:01.936+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-15T17:42:01.949+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-15T17:42:01.989+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=gen_data_daily, task_id=calcaulte_fts, execution_date=20250313T220000, start_date=20250315T174123, end_date=20250315T174201
[2025-03-15T17:42:02.023+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task calcaulte_fts (Bash command failed. The command returned a non-zero exit code 1.; 1899)
[2025-03-15T17:42:02.046+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-15T17:42:02.085+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
