[2025-03-15T17:56:10.792+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.calcaulte_fts scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-03-15T17:56:10.808+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.calcaulte_fts scheduled__2025-03-13T22:00:00+00:00 [queued]>
[2025-03-15T17:56:10.808+0000] {taskinstance.py:2171} INFO - Starting attempt 4 of 5
[2025-03-15T17:56:10.825+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): calcaulte_fts> on 2025-03-13 22:00:00+00:00
[2025-03-15T17:56:10.833+0000] {standard_task_runner.py:60} INFO - Started process 2608 to run task
[2025-03-15T17:56:10.838+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'calcaulte_fts', 'scheduled__2025-03-13T22:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpj_dk1jou']
[2025-03-15T17:56:10.841+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask calcaulte_fts
[2025-03-15T17:56:10.924+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.calcaulte_fts scheduled__2025-03-13T22:00:00+00:00 [running]> on host 1e3bcc32b6c1
[2025-03-15T17:56:11.044+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='calcaulte_fts' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T22:00:00+00:00'
[2025-03-15T17:56:11.045+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-15T17:56:11.046+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/2_calculate_features.py 2025-03-14\n        ']
[2025-03-15T17:56:11.064+0000] {subprocess.py:86} INFO - Output:
[2025-03-15T17:56:21.055+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-03-15T17:56:21.322+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-03-15T17:56:21.323+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-03-15T17:56:21.333+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-03-15T17:56:21.333+0000] {subprocess.py:93} INFO - io.delta#delta-core_2.12 added as a dependency
[2025-03-15T17:56:21.334+0000] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-03-15T17:56:21.334+0000] {subprocess.py:93} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-03-15T17:56:21.334+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-041106d9-df7c-48d8-a9e2-41b971ed4b10;1.0
[2025-03-15T17:56:21.334+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-03-15T17:56:21.779+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 in central
[2025-03-15T17:56:21.912+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 in central
[2025-03-15T17:56:21.977+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;3.3.2 in central
[2025-03-15T17:56:22.060+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-03-15T17:56:22.087+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.10.1 in central
[2025-03-15T17:56:22.097+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;2.0.6 in central
[2025-03-15T17:56:22.139+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-03-15T17:56:22.166+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-03-15T17:56:22.207+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-03-15T17:56:22.234+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-03-15T17:56:22.255+0000] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-03-15T17:56:22.283+0000] {subprocess.py:93} INFO - 	found io.delta#delta-core_2.12;2.4.0 in central
[2025-03-15T17:56:22.305+0000] {subprocess.py:93} INFO - 	found io.delta#delta-storage;2.4.0 in central
[2025-03-15T17:56:22.316+0000] {subprocess.py:93} INFO - 	found org.antlr#antlr4-runtime;4.9.3 in central
[2025-03-15T17:56:22.384+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in central
[2025-03-15T17:56:22.424+0000] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-03-15T17:56:22.438+0000] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.12.261 in central
[2025-03-15T17:56:22.469+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 1114ms :: artifacts dl 19ms
[2025-03-15T17:56:22.471+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-03-15T17:56:22.471+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.12.261 from central in [default]
[2025-03-15T17:56:22.471+0000] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-03-15T17:56:22.471+0000] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-03-15T17:56:22.472+0000] {subprocess.py:93} INFO - 	io.delta#delta-core_2.12;2.4.0 from central in [default]
[2025-03-15T17:56:22.472+0000] {subprocess.py:93} INFO - 	io.delta#delta-storage;2.4.0 from central in [default]
[2025-03-15T17:56:22.472+0000] {subprocess.py:93} INFO - 	org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2025-03-15T17:56:22.472+0000] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-03-15T17:56:22.472+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from central in [default]
[2025-03-15T17:56:22.473+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2025-03-15T17:56:22.473+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-03-15T17:56:22.473+0000] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;3.3.2 from central in [default]
[2025-03-15T17:56:22.473+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-03-15T17:56:22.473+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.1 from central in [default]
[2025-03-15T17:56:22.474+0000] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-03-15T17:56:22.474+0000] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;2.0.6 from central in [default]
[2025-03-15T17:56:22.475+0000] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-03-15T17:56:22.475+0000] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.10.1 from central in [default]
[2025-03-15T17:56:22.475+0000] {subprocess.py:93} INFO - 	:: evicted modules:
[2025-03-15T17:56:22.475+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 by [com.amazonaws#aws-java-sdk-bundle;1.12.261] in [default]
[2025-03-15T17:56:22.475+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-03-15T17:56:22.475+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-03-15T17:56:22.476+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-03-15T17:56:22.476+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-03-15T17:56:22.476+0000] {subprocess.py:93} INFO - 	|      default     |   18  |   0   |   0   |   1   ||   17  |   0   |
[2025-03-15T17:56:22.476+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-03-15T17:56:22.487+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-041106d9-df7c-48d8-a9e2-41b971ed4b10
[2025-03-15T17:56:22.487+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-03-15T17:56:22.500+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 17 already retrieved (0kB/16ms)
[2025-03-15T17:56:23.491+0000] {subprocess.py:93} INFO - 25/03/15 17:56:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-15T17:56:24.207+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-03-15T17:56:24.208+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-15T17:56:59.146+0000] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 1][Stage 0:>                                                          (0 + 1) / 1]                                                                                kafka:29092 transaction_data
[2025-03-15T17:56:59.147+0000] {subprocess.py:93} INFO - http://minio:9000 transaction-data
[2025-03-15T17:56:59.147+0000] {subprocess.py:93} INFO - +-------+--------------+------+------+-------+----+---------+----+
[2025-03-15T17:56:59.147+0000] {subprocess.py:93} INFO - |User ID|Transaction ID|Amount|Vendor|Sources|Time|timestamp|date|
[2025-03-15T17:56:59.147+0000] {subprocess.py:93} INFO - +-------+--------------+------+------+-------+----+---------+----+
[2025-03-15T17:56:59.147+0000] {subprocess.py:93} INFO - +-------+--------------+------+------+-------+----+---------+----+
[2025-03-15T17:56:59.148+0000] {subprocess.py:93} INFO - 
[2025-03-15T17:56:59.172+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-15T17:56:59.173+0000] {subprocess.py:93} INFO -   File "/opt/***/external_scripts/2_calculate_features.py", line 84, in <module>
[2025-03-15T17:56:59.173+0000] {subprocess.py:93} INFO -     minio_client = Minio(
[2025-03-15T17:56:59.173+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/minio/api.py", line 135, in __init__
[2025-03-15T17:56:59.176+0000] {subprocess.py:93} INFO -     self._base_url = BaseURL(
[2025-03-15T17:56:59.176+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/minio/helpers.py", line 443, in __init__
[2025-03-15T17:56:59.176+0000] {subprocess.py:93} INFO -     raise ValueError("path in endpoint is not allowed")
[2025-03-15T17:56:59.176+0000] {subprocess.py:93} INFO - ValueError: path in endpoint is not allowed
[2025-03-15T17:56:59.220+0000] {subprocess.py:93} INFO - Exception ignored in: <function Minio.__del__ at 0x71b344ba1040>
[2025-03-15T17:56:59.220+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-15T17:56:59.221+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/minio/api.py", line 160, in __del__
[2025-03-15T17:56:59.222+0000] {subprocess.py:93} INFO -     self._http.clear()
[2025-03-15T17:56:59.222+0000] {subprocess.py:93} INFO - AttributeError: 'Minio' object has no attribute '_http'
[2025-03-15T17:56:59.973+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-15T17:57:00.001+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-15T17:57:00.029+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=gen_data_daily, task_id=calcaulte_fts, execution_date=20250313T220000, start_date=20250315T175610, end_date=20250315T175700
[2025-03-15T17:57:00.064+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task calcaulte_fts (Bash command failed. The command returned a non-zero exit code 1.; 2608)
[2025-03-15T17:57:00.120+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-15T17:57:00.224+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
