[2025-03-22T18:18:56.235+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-06T22:00:00+00:00 [queued]>
[2025-03-22T18:18:56.250+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-06T22:00:00+00:00 [queued]>
[2025-03-22T18:18:56.250+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2025-03-22T18:18:56.272+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-06 22:00:00+00:00
[2025-03-22T18:18:56.286+0000] {standard_task_runner.py:60} INFO - Started process 6086 to run task
[2025-03-22T18:18:56.293+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-06T22:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp0sm4i9au']
[2025-03-22T18:18:56.295+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask gen_data_daily
[2025-03-22T18:18:56.370+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-06T22:00:00+00:00 [running]> on host 8d12aff548d4
[2025-03-22T18:18:56.527+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-06T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-06T22:00:00+00:00'
[2025-03-22T18:18:56.529+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-22T18:18:56.530+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-07\n        ']
[2025-03-22T18:18:56.550+0000] {subprocess.py:86} INFO - Output:
[2025-03-22T18:18:58.741+0000] {subprocess.py:93} INFO - Successfully inserted 20000 rows into transaction_data table at 2025-03-07
[2025-03-22T18:18:58.741+0000] {subprocess.py:93} INFO - Table contains 140000 rows
[2025-03-22T18:18:58.742+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-07
[2025-03-22T18:18:58.904+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-22T18:18:58.967+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250306T220000, start_date=20250322T181856, end_date=20250322T181858
[2025-03-22T18:18:59.009+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-22T18:18:59.036+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
