[2025-03-22T18:18:40.495+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-03T22:00:00+00:00 [queued]>
[2025-03-22T18:18:40.538+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-03T22:00:00+00:00 [queued]>
[2025-03-22T18:18:40.542+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2025-03-22T18:18:40.587+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-03 22:00:00+00:00
[2025-03-22T18:18:40.599+0000] {standard_task_runner.py:60} INFO - Started process 6053 to run task
[2025-03-22T18:18:40.609+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-03T22:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp9zbqlrk8']
[2025-03-22T18:18:40.612+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask gen_data_daily
[2025-03-22T18:18:40.714+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-03T22:00:00+00:00 [running]> on host 8d12aff548d4
[2025-03-22T18:18:40.912+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T22:00:00+00:00'
[2025-03-22T18:18:40.913+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-22T18:18:40.915+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-04\n        ']
[2025-03-22T18:18:40.949+0000] {subprocess.py:86} INFO - Output:
[2025-03-22T18:18:43.377+0000] {subprocess.py:93} INFO - Successfully inserted 20000 rows into transaction_data table at 2025-03-04
[2025-03-22T18:18:43.378+0000] {subprocess.py:93} INFO - Table contains 80000 rows
[2025-03-22T18:18:43.378+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-04
[2025-03-22T18:18:43.514+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-22T18:18:43.681+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250303T220000, start_date=20250322T181840, end_date=20250322T181843
[2025-03-22T18:18:43.731+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-22T18:18:43.759+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
